// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MusicManager.Models;
using System;

namespace MusicManager.Migrations
{
    [DbContext(typeof(MusicManagerContext))]
    [Migration("20180601123815_TrackMapping")]
    partial class TrackMapping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusicManager.Models.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("MusicManager.Models.MusicTrack", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArtistID");

                    b.Property<int>("Length");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("MusicTrack");
                });

            modelBuilder.Entity("MusicManager.Models.PlayList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PlayList");
                });

            modelBuilder.Entity("MusicManager.Models.TrackPlaylistMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlaylistID");

                    b.Property<int>("TrackID");

                    b.HasKey("ID");

                    b.ToTable("TrackPlaylistMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
